### ISSUE TITLE
How do I make this work?

### ISSUE THREAD

**Issue by NigelXheri** [xNasuni/artlist-downloader#1]
First of all don't mind if my question is dumb since I have little to no knowledge about this topic.

I clicked on install userscript and it showed me an error saying that you can't add an extension from this site. 
So I added the extension and when I clicked install userscript. A tampermonkey prompt appeared in a new window which asked if I want to install the script. I installed the script on tampermonkey and made sure it was enabled. Also, after opening the artlist.io website a little red dot appeared on the tampermonkey extension which means that it is running correctly.

When I click to play a music there isn't any pop-up asking me if I want to download the music.

Did I miss something?
![image](https://github.com/xNasuni/artlist-downloader/assets/76738080/67c20a60-2ba1-483a-bcc8-41c86f9d4b8e)

**Comment by xNasuni** [comment]
should be fixed in 540a4dc but it might be annoying, unfortunately i couldn't find any easier way then what it is now, i will update the readme in a second but basically every time a song gets precached it will notify you if you want to save it as a file, and it will put the file name and i can't really get the name of the song instead so it might be annoying but if you can search through all the notifications for the certain file name that looks like the one you are trying to download then you can click on it and save it, if not you can go to the first one on top, click it and press escape instantly and it will close the save file dialog, and you can do that until you can see new ones at the bottom since it clips out of the screen, let me know if it works so i can close this

**Comment by xNasuni** [comment]
now it should be easier for you because of #2 being fixed
