### ISSUE TITLE
How the hell should I use this? 

### ISSUE THREAD

**Issue by gogunow** [xNasuni/artlist-downloader#5]
Can you please provide ANY clue how to use this script? What should I do with file I downloaded? How can be so delusional to think that anyone can understand what to do with .js files if they are even can't open the dev console?

**Comment by xNasuni** [comment]
you aren't really meant to use the dev console, you are meant to use a userscript manager which is an extension that can run scripts when websites load which is mostly self evident by the mentions of the words "userscript".

you can install a userscript manager such as [**Tampermonkey**](https://github.com/Tampermonkey/tampermonkey) or [**Violentmonkey**](https://github.com/violentmonkey/violentmonkey)

i didn't mention this as i thought that anyone using something like this, would already have a userscript manager or atleast know what it is, install this extension and then install this userscript and tell me if it works.

this userscript is half broken anyway and i don't have the motivation to work on this right now since i'm doing way more important things in real life and there isn't much people using it as far as i know so i didn't feel rushed to fix the issues.

**Comment by arslanmahmooddexter** [comment]
Thank you xNasuni for your work. I did manage to install the code through tampermonkey. But looks like nothing is happening on artlist page after playing any track.

**Comment by xNasuni** [comment]
the download buttons should turn green, if they do then you should be able to click them and they should download the song

**Comment by arslanmahmooddexter** [comment]
Thank you xNasuni, working now

**Comment by arslanmahmooddexter** [comment]
My bad, its not working or maybe i dont know how to use it. But thanks for your effect.

**Comment by xNasuni** [comment]
when you go to the page, the music buttons should simply turn green, when you press them it should download the music in a **aac** format, you can use an online converter but i'm simply just downloading what the website is playing which works perfectly for me, lmk if you still have issues or the buttons don't turn green, if they dont try seeing if there's any errors in the developer consoler

**Comment by xNasuni** [comment]
when you go to the page, the music buttons should simply turn green, when you press them it should download the music in a **aac** format, you can use an online converter but i'm simply just downloading what the website is playing which works perfectly for me, lmk if you still have issues or the buttons don't turn green, if they dont try seeing if there's any errors in the developer consoler
